miproyecto/FlaskApp/routes/admin.py
from flask import Blueprint
from flask_login import login_required
from utilidad import requiere_rol



'''login_requerid nos garantiza que solo los usuarios
auutenticados pueden acceder a esta ruta'''

admin_bp = Blueprint('admin', __name__)
@admin_bp.route('/admin')

@login_required 
@requiere_rol(['administrador'])
def admin():
    from flask import render_template
    return render_template ('admin.html')

miproyecto/FlaskApp/routes/cajero.py
from flask import Blueprint
from flask_login import login_required
from utilidad import requiere_rol

cajero_bp = Blueprint('cajero',__name__)

@cajero_bp.route('/cajero')
@requiere_rol(['administrador','cajero'])
@login_required
def cajero():
    from flask import render_template
    return render_template('cajero.html')

miproyecto/FlaskApp/routes/cocinero.py
from flask import Blueprint
from flask_login import login_required
from utilidad import requiere_rol

cocinero_bp = Blueprint('cocinero',__name__)
@cocinero_bp.route('/cocinero')
@login_required
@requiere_rol(['cocinero','administrador'])
def cocinero():
    from flask import render_template
    return render_template('cocinero.html')

miproyecto/FlaskApp/routes/dashboard.py
from flask import Blueprint
from flask_login import login_required



'''login_requerid nos garantiza que solo los usuarios
auutenticados pueden acceder a esta ruta'''

dashboard_bp = Blueprint('dashboard', __name__)
@dashboard_bp.route('/dashboard')
@login_required 

def dashboard():
    
    from flask import render_template
    return render_template ('dashboard.html')

miproyecto/FlaskApp/routes/login.py
from flask import Flask, Blueprint, render_template, url_for, flash, redirect
from config import app, mysql
from flask_bcrypt import Bcrypt
from flask_login import login_user, current_user
from models import Usuario, control_rol
from formularios.forms import LoginForm


bcrypt = Bcrypt(app)

login_bp = Blueprint ('login', __name__)

@login_bp.route('/login', methods=['GET','POST'])

def login():
    
    form = LoginForm()

    if form.validate_on_submit():
        
        email = form.email.data
        contraseña = form.contraseña.data

        """En esta seccion no hace falta utilizar el metodo
         brypt.generate_password_hash ya que lo que debo
         realizar es una comprabacion de la contraseña 
         ingresada en el formulario de login para validar 
         si coincide con la de la BD"""
        
        cur = mysql.connection.cursor()

        cur.execute('SELECT * FROM usuarios WHERE email= %s',(email,))
        usuario = cur.fetchone()
        cur.close()

        '''Con bcrypt.check_password_hash validamos si la
        contraseña incriptada en la base de datos es la 
        misma que la ingresa por el usuario.'''

        if usuario and bcrypt.check_password_hash(usuario['contraseña'],contraseña):

            user = Usuario (usuario['id_usuario'],usuario['nombre'],usuario['apellido']
            ,usuario['telefono'],usuario['email'],
            usuario['contraseña'])
            
            '''Inicia Sesion. Estable la sesion del usuario'''
            login_user(user) 
            
            if current_user.is_authenticated:
                control= control_rol(current_user.id)
                roles= control.obtener_roles()
                print(roles)
            else:
                print('Usuario no autenticado...')    


            if 'cajero' in roles and 'mesero' in roles:
             flash('Pagina para la gestion de pedidos en construccion...','success')
             return redirect(url_for('mesero.mesero'))

            elif 'administrador' in roles:
             flash('Bienvenid@ Pagina del Administrador en contruccion...','success')
             return redirect(url_for('admin.admin'))

            elif 'mesero' in roles:
             flash('Pagina para la gestion de pedidos en construccion...','success')
             return redirect(url_for('mesero.mesero'))

            elif 'cajero' in roles:
             flash('Pagina para la gestion de pedidos y facturacion en construccion...','success')
             return redirect(url_for('cajero.cajero'))

            elif 'cocinero' in roles:
             flash('Pagina para la gestion en la cocina en construccion...','success')
             return redirect(url_for('cocinero.cocinero'))
        
        else:
            flash("Correo o contraseña incorrectos.", "danger")

    return render_template ('login.html', form=form)

miproyecto/FlaskApp/routes/logout.py
from flask import Blueprint
from flask_login import logout_user

logout_bp = Blueprint('logout', __name__)
@logout_bp.route('/logout')

def logout():
    from flask import redirect, url_for, flash
    
    logout_user()  # Cierra la sesión
    flash("Sesión cerrada correctamente", "info")
    return redirect(url_for('login.login'))

miproyecto/FlaskApp/routes/mesero.py
from flask import Blueprint
from flask_login import login_required
from utilidad import requiere_rol

mesero_bp = Blueprint('mesero',__name__)
@mesero_bp.route('/mesero')

@requiere_rol(['administrador','mesero'])
@login_required
def mesero():
    from flask import render_template
    return render_template('mesero.html')

miproyecto/FlaskApp/routes/registro.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from config import app, mysql
from flask_bcrypt import Bcrypt
from formularios.forms import RegistroForm

bcrypt = Bcrypt(app)

registro_bp = Blueprint('registro', __name__)

@registro_bp.route('/registro', methods=['GET', 'POST'])

def registro():

    '''Utilizamos la libreria Flask-WTF para
    la validacion y renderizacion de los formularios'''

    form = RegistroForm()
    
    #print("request.method:", request.method)   Muestra si es POST o GET
    #print("request.form:", request.form)   Verifica qué datos está enviando el formulario
    #print("CSRF Token:", request.form.get("csrf_token"))   Revisa si el token se está enviando
    
    if form.validate_on_submit():
        '''En esta seccion capturamos las datos enviados
        por medio del formulario y lo almancenamos en 
        variables para sus posterior uso'''
     

        nombre = form.nombre.data
        apellido = form.apellido.data
        telefono = form.telefono.data
        email = form.email.data
        contraseña = form.contraseña.data

        '''En esta variable por medio de la libreria
        brypt incriptamos la  antes de almacenarla
         para que sea mas segura'''
        contraseña_incriptada = bcrypt.generate_password_hash(contraseña).decode('utf-8')

        """Usamos sentencias sql para insertar los
        datos del formulario en la tabla de la base de datos,
        se crea una variable y se guarda la conexion"""

        cur = mysql.connection.cursor()
        cur.execute("INSERT INTO usuarios (nombre, apellido, email, contraseña) VALUES (%s, %s, %s, %s)", 
                    (nombre, apellido, email, contraseña_incriptada))
        mysql.connection.commit()
        cur.close() 
        flash("Registro exitoso. Ahora puedes iniciar sesión.", "success")
        
        return redirect(url_for('registro.registro'))

    return render_template('registro.html', form=form)

miproyecto/FlaskApp/templates/admin.html
{% extends 'base.html' %}

{% block title %}Panel de Administracion{% endblock %}

{% block content %}
 <h1 class="text-center text-primary">Panel de control del Administrador</h1>
 
 {% if current_user.is_authenticated %}
  <p class="fs-3 fw-bold">Bienveni@ {{current_user.nombre}} {{current_user.apellido}}</p>
 {% else %}
  <a href="{{url_for('login.login')}}">Inicie Sesion</a>
 {% endif %}

 
 <div class="mt-3">
    <a href="{{url_for('logout.logout')}}" class="btn btn-secondary">Cerrar Sesion</a>
    <a href="{{url_for('cajero.cajero')}}" class="btn btn-primary">Gestion de Caja</a>
    <a href="{{url_for('mesero.mesero')}}" class="btn btn-info">Gestion de Mesas</a>
    <a href="{{url_for('cocinero.cocinero')}}" class="btn btn-warning">Gestion de Cocina</a>
 </div>
{% endblock %}

miproyecto/FlaskApp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}-Gestion de pedidos-{% endblock %}</title>
    <!---Bootstrap CSS JS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    {% block head %}{% endblock %}
</head>
<body style="background-color:rgb(245, 225, 200);">
    <!--Header superior-->
    <nav class="navbar bg-dark">
        <div class="container-fluid d-flex justify-content-center align.items-center">
          <span class="navbar-brand text-light fs-4 fw-bold">Al Sabor Misionero</span>
            <img src="{{url_for('static',filename='img/logoalsabormisionero.PNG')}}" 
            alt="Logo" width="50" height="80" 
            class=" ms-3 d-inline-block align-text-bottom">
         
        </div>
    </nav>

    <!--Menu de navegacion-->
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand text-dark" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            {% if current_user.is_authenticated %}
             <li class="nav-item">
               <a class="nav-link active" aria-current="page" href="{{url_for('logout.logout')}}">Cerrar sesion</a>
             </li>
            <!--Aqui van las otras vistas-->
             <li class="nav-item">
               <a class="nav-link" href="{{url_for('admin.admin')}}">Administracion</a>
             </li>
             <li class="nav-item">
               <a class="nav-link" href="{{url_for('cajero.cajero')}}">Cajeros</a>
             </li>
             <li class="nav-item">
               <a class="nav-link" href="{{url_for('mesero.mesero')}}">Meseros</a>
             </li>
             <li class="nav-item">
              <a class="nav-link" href="{{url_for('cocinero.cocinero')}}">cocinero</a>
            </li>
            {% else %}
             <li class="nav-item">
               <a class="nav-link" href="{{url_for('login.login')}}">Inicie sesion</a>
              <!--<a class="nav-link disabled" aria-disabled="true">Disabled</a>-->
             </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <!--Contenedor principal-->
    <div class="container mt-4">
    <!--Mensajes Flash para cada pagina-->
    {% with messages = get_flashed_messages (with_categories= true) %}
     {% if messages %} 
        {% for category, message in messages %} 
        <div class="alert alert-{{category}} alert dismissible fade show" role="alert">
          {{message}}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
     {% endif %}
    {% endwith %}

    <!--Contenido especifico de cada vista-->
    {% block content %}{% endblock %}
    </div>


</body>
</html>

miproyecto/FlaskApp/templates/cajero.html
{% extends "base.html" %}

{% block title %}Panel de Cajero{% endblock %}

{% block content %}
  <h2>Panel de Control de Cajero</h2>
  
  {% if current_user.is_authenticated %}
    <p>Bienvenid@ {{ current_user.nombre }}</p>
  {% else %}
    <a href="{{ url_for('login.login') }}">Inicie Sesion</a>
  {% endif %}

  <div class="mt-3">
    <a href="{{ url_for('logout.logout') }}" class="btn btn-secondary">Cerrar Sesión</a>
    <a href="{{ url_for('mesero.mesero') }}" class="btn btn-info">Gestión de pedidos</a>
  </div>
{% endblock %}

miproyecto/FlaskApp/templates/cocinero.html
{% extends "base.html" %}

{% block title %}Panel de Control de Cocina{% endblock %}

{% block content %}
  <h1>Panel de Control de Cocina</h2>
  
  {% if current_user.is_authenticated %}
    <p>Bienvenid@ {{ current_user.nombre }}</p>
  {% else %}
    <a href="{{ url_for('login.login') }}">Solo usuarios autenticados pueden ingresar...</a>
  {% endif %}

  <div class="mt-3">
    <a href="{{ url_for('logout.logout') }}" class="btn btn-secondary">Cerrar Sesión</a>
  </div>
{% endblock %}

miproyecto/FlaskApp/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
</head>
<body>
    <h2>Pagina protegida</h2>
    
    {% with messages = get_flashed_messages (with_categories= true) %}
     {% if messages %} 
        {% for category, message in messages %} 
         <p class="{{ category }}">{{ message }}</p>
        {% endfor %}
     {% endif %}
    {% endwith %}

    <a href="{{url_for('logout.logout')}}">Cierre Sesion</a>


</body>
</html>

miproyecto/FlaskApp/templates/login.html
{% extends 'base.html' %}

{% block title %}Inicio de Sesion de Usuarios Registrados{% endblock %}

{% block content %} 
<h1>Iniciar Sesion</h1>

<form action="" method="POST" novalidate>
    
    {{ form.hidden_tag() }}

    <div class="">
        {{form.email.label}} <br>
        {{form.email(size=32)}}

        {% if form.email.errors %}
         {% for error in form.email.errors %}
          <span class="text-danger"> {{ error }}</span>
         {% endfor %}
        {% endif %}

    </div>

    <div class="mb-3">
        {{form.contraseña.label}} <br>
        {{form.contraseña(size=32)}} 

        {% if form.email.errors %}
         {% for error in form.email.errors %}
          <span class="text-danger"> {{ error }}</span>
         {% endfor %}
        {% endif %}
    </div>

    <div>
        {{ form.submit(class="btn btn-primary") }}
    </div>
</form>
<a href="{{url_for('registro.registro')}}">¿No tienes un cuenta? Registrate!!</a>


{% endblock %}
    
    

miproyecto/FlaskApp/templates/mesero.html
{% extends 'base.html' %}

{% block title %}Panel de control de Mesero{% endblock %}

{% block content %}
 <h1 class="fw-bold">Panel de control de Pedidos- Mesero</h1>

 {% if current_user.is_authenticated %}
  <p class="fw-bold">Bienvenid@ {{current_user.nombre}}</p> 
 {% else %}
  <a href="{{url_for('login.login')}}">Inicie Sesion</a>
 {% endblock %}
 {% endif %}

 <div class="mt-3"></div>
 <a href="{{url_for('logout.logout')}}">Cerrar Sesion</a>
 <a href="{{url_for('cajero.cajero')}}">Gestion de Caja</a>
 {% endblock %}

miproyecto/FlaskApp/templates/registro.html
{% extends 'base.html '%}
{% block title %} Registro de Usuarios {% endblock %}

{%block content %}

<h2 class="text-center fw-bold">Registro de Usuarios</h2>

<!--Mensajes Flash del Backend-->
{% for category,message in get_flashed_messages(with_categories=true)%}
 <p class="success" style="font-family: Verdana, Geneva, Tahoma, sans-serif;
 font-size: 20px;color: green;">{{message}}</p>
{% endfor %}

<!-- Formulario de registro -->
<form method="POST" NOVALIDATE class="d-flex flex-column align-items-center">
    
    {{ form.hidden_tag() }}
  
  <div class="w-50">

    <div  class="mb-3">
        {{form.nombre.label(class="form-label")}} {{form.nombre(class="form-control")}}

        {% if form.nombre.errors%}
         {% for error in form.nombre.errors %}
          <span class="text-danger">{{error}}</span>
         {% endfor %}
        {% endif %}

    </div>

    <div  class="mb-3">
        {{form.apellido.label(class="form-label")}} {{form.apellido(class="form-control")}}
            
        {% if form.apellido.errors %}
         {% for error in form.apellido.errors %}
         <span class="text-danger">{{error}}</span>
         {% endfor %}
        {% endif %}

    </div>

    <div  class="mb-3">
        {{form.email.label(class="form-label")}} {{form.email(class="form-control")}}

        {% if form.email.errors%}
         {% for error in form.email.errors %}
         <span class="text-danger">{{error}}</span>
         {% endfor %}
        {% endif %}

    </div>

    <div  class="mb-3">
        {{form.telefono.label(class="form-label")}} {{form.telefono(class="form-control")}}
        
        {% if form.telefono.errors %}
         {% for error in form.telefono.errors %}
         <span class="text-danger">{{error}}</span>
         {% endfor %}
        {% endif %}
        
    </div>


    <div class="mb-3">
        {{form.contraseña.label(class="form-label")}} {{form.contraseña(class="form-control")}}
        
        {% if form.contraseña.errors %}
         {% for error in form.contraseña.errors %}
         <span class="text-danger">{{error}}</span>
         {% endfor %}
        {% endif %}
        
    </div>

    <div class="mb-3">
        {{form.confirmar_contraseña.label(class="form-label")}} {{form.confirmar_contraseña(class="form-control")}}
        
        {% if form.confirmar_contraseña.errors %}
         {% for error in form.confirmar_contraseña.errors %}
         <span class="text-danger">{{error}}</span>
         {% endfor %}
        {% endif %}
        
    </div>

    
    <div class="mb-3 text-center">
        {{form.submit(class="btn btn-primary w-100")}}
    </div>
   </div>
</form>

<a href="{{url_for('login.login')}}"
class="d-block text-center mb-3 ">
¿Ya tienes una cuenta? Iniciar sesion</a>

{% endblock %}

    